export const siteMetadata = {
  name: 'Fuzzy SAW Lab',
  shortName: 'Fuzzy SAW Lab',
  tagline: 'Laboratorium Keputusan Fuzzy SAW yang menampilkan ranking paling objektif.',
  description:
    'Fuzzy SAW Lab adalah laboratorium keputusan berbasis metode Fuzzy Simple Additive Weighting (SAW) untuk menyusun ranking alternatif, menormalkan bobot, dan menjaga transparansi perhitungan TFN.',
  keywords: [
    'fuzzy saw',
    'fuzzy greenflag',
    'fuzzy saw greenflag',
    'fuzzy saw laboratorium',
    'greenflag fuzzy lab',
    'laboratorium fuzzy',
    'triangular fuzzy number',
    'sistem pendukung keputusan',
    'decision support system',
    'normalisasi bobot',
    'ranking alternatif',
    'fsaw detection',
    'multi criteria decision making',
    'laboratorium keputusan fuzzy',
    'fuzzy skipsi',
    'greenflag decision lab',
    'deteksi fuzzy greenflag',
    'fuzzy saw laboratory',
    'laboratorium fuzzy saw',
  ],
  author: 'Wahyu Pratama',
  publisher: 'Fuzzy SAW Lab',
  locale: 'id_ID',
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://tfsaw-greenflag.vercel.app',
  socialImage: '/showcred.png',
  twitterHandle: '@fuzzysawlab',
};
